version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: redlinegt-wire-pod_app_1
      APP_PORT: 8080

  app:
    image: ghcr.io/redlinegt/wire-pod:1.0.0@sha256:224bc28014f6eb5ccb2e373605f13be4dde9e5cae414f6699e18bb10e49d9259
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
      - "8084:8084"
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      WIREPOD_DATA_DIR: /data
      WIREPOD_DEBUG_LOGGING: "true"
      WIREPOD_STT_SERVICE: "vosk"
      WIREPOD_STT_LANGUAGE: "en-US"
      WIREPOD_USE_INBUILT_BLE: "false"
    networks:
      - default

networks:
  default:
    driver: bridge
